export default books = 
[{"title":"Big Year, The","author":"Kristyn Stolze","pages":274,"price":30.45},
    {"title":"Flawless","author":"Jolee Philliskirk","pages":546,"price":39.53},
    {"title":"Fish Tank","author":"Chase Chalfain","pages":36,"price":57.84},
    {"title":"Horror Business","author":"Jessie Mancktelow","pages":301,"price":41.55},
    {"title":"Little Witches","author":"Meade Dyott","pages":248,"price":48.94},
    {"title":"Sling Blade","author":"Royall Rubenczyk","pages":28,"price":3.55},
    {"title":"Maborosi (Maboroshi no hikari)","author":"Raven Carden","pages":586,"price":41.06},
    {"title":"Vampire in Brooklyn","author":"Nadya Swayton","pages":460,"price":27.43},
    {"title":"Ninja Scroll (Jûbei ninpûchô)","author":"Morgen Carriage","pages":222,"price":46.26},
    {"title":"Thousand Acres, A","author":"Harmonia Pulfer","pages":479,"price":28.47},
    {"title":"Neds","author":"Marlene Dunlap","pages":281,"price":35.74},
    {"title":"Wimbledon","author":"Angus Toolan","pages":578,"price":43.8},
    {"title":"Beast Must Die, The","author":"Dre MacDonald","pages":336,"price":9.04},
    {"title":"Anthony Adverse","author":"Ramsay Grosvenor","pages":481,"price":13.16},
    {"title":"I Love Trouble","author":"Michaelina Rhymer","pages":367,"price":38.25},
    {"title":"Takva: A Man's Fear of God","author":"Nickolaus Pennone","pages":123,"price":23.38},
    {"title":"Senotaji","author":"Yehudit Thrower","pages":28,"price":24.24},
    {"title":"Woman Rebels, A (Portrait of a Rebel)","author":"Alisha McNeachtain","pages":120,"price":2.72},
    {"title":"Oliver Twist","author":"Hurleigh Ducrow","pages":503,"price":45.14},
    {"title":"Beyond the Valley of the Dolls","author":"Brena Harraway","pages":487,"price":48.69},
    {"title":"Miracle on 34th Street","author":"Ginny Frisel","pages":158,"price":18.47},
    {"title":"Needing You... (Goo naam gwa neui)","author":"Nate Bannard","pages":300,"price":4.7},
    {"title":"Metsän tarina","author":"Hazlett Dockreay","pages":447,"price":48.52},
    {"title":"Cats","author":"Humphrey Idill","pages":408,"price":11.5},
    {"title":"Caesar (Julius Caesar)","author":"Kristel Nickols","pages":444,"price":17.8},
    {"title":"Sandor slash Ida","author":"Pier Toxell","pages":343,"price":20.0},
    {"title":"Don't Look Now","author":"Neddie Brompton","pages":363,"price":41.9},
    {"title":"Courage Mountain","author":"Cloris Graham","pages":344,"price":10.13},
    {"title":"Suburbans, The","author":"Luci McKomb","pages":338,"price":35.02},
    {"title":"Spread","author":"Windham Sillars","pages":346,"price":30.29},
    {"title":"Party Monster","author":"Barbi Quickenden","pages":190,"price":39.83},
    {"title":"Shattered Glass","author":"Christopher Santry","pages":192,"price":46.33},
    {"title":"Private War of Major Benson, The","author":"Jacklyn Duthie","pages":423,"price":57.25},
    {"title":"The Runner from Ravenshead","author":"Kendrick Smithies","pages":227,"price":48.32},
    {"title":"Shadows","author":"Guilbert Markson","pages":267,"price":12.53},
    {"title":"Faces of Death","author":"Leonanie Ceci","pages":265,"price":48.91},
    {"title":"Elephant White","author":"Odie Seivertsen","pages":288,"price":43.44},
    {"title":"Upside Down","author":"Bennett Stanbro","pages":31,"price":25.79},
    {"title":"F/X2 (a.k.a. F/X 2 - The Deadly Art of Illusion)","author":"Vida Capey","pages":322,"price":8.75},
    {"title":"Forest of the Gods (Dievu miskas)","author":"Selby Portsmouth","pages":236,"price":29.88},
    {"title":"Dinner at Eight","author":"Libbey Rykert","pages":372,"price":27.21},
    {"title":"Element of Crime, The (Forbrydelsens Element)","author":"Corenda Aldie","pages":406,"price":23.6},
    {"title":"Hackers","author":"Allyce Duckham","pages":159,"price":28.47},
    {"title":"Black Sheep","author":"Lind Neiland","pages":310,"price":23.08},
    {"title":"Little Romance, A","author":"Richard Popeley","pages":350,"price":13.63},
    {"title":"Louis Theroux: Twilight of the Porn Stars","author":"Carlin Edelmann","pages":191,"price":12.61},
    {"title":"Razor's Edge, The","author":"Lorenzo Lauxmann","pages":92,"price":58.52},
    {"title":"Lamp in the Dark; The Untold History of the Bible, A","author":"Chauncey Scarlon","pages":62,"price":54.48},
    {"title":"Playing with Love (Puppy Love) (Maladolescenza)","author":"Bel Tonsley","pages":415,"price":47.03},
    {"title":"Mutant Action (Acción Mutante)","author":"Carlie Clarey","pages":587,"price":1.66}
]